<?hh //strict

namespace PayPal\Constants;

enum EventType:string
{
    INVOICE_CANCELLED       = 'INVOICING.INVOICE.CANCELLED';
    INVOICE_PAID            = 'INVOICING.INVOICE.PAID';
    INVOICE_REFUNDED        = 'INVOICING.INVOICE.REFUNDED';
    SALE_COMPLETED          = 'PAYMENT.SALE.COMPLETED';
    SALE_DENIED             = 'PAYMENT.SALE.DENIED';
    SALE_PENDING            = 'PAYMENT.SALE.PENDING';
    SALE_REFUNDED           = 'PAYMENT.SALE.REFUNDED';
    SALE_REVERSED           = 'PAYMENT.SALE.REVERSED';
    PAYMENT_AUTH_CREATED    = 'PAYMENT.AUTHORIZATION.CREATED';
}
